GET http://localhost:5000/admin

####
GET http://localhost:5000/admin
Authorization: cat
####
GET http://localhost:5000/expenses

####
POST http://localhost:5000/expenses
Content-Type: application/json

{
    "category": "Jedzenie",
    "date": "2022-09-28",
    "kwota": 66.5,
    "title": "Sih"

}


####
POST http://localhost:5000/expenses
Content-Type: application/json

{

  "date": "2022-09-28",
  "kwota": 66,
  "title": "Sio kwota",
  "opis": "jas opis"
}

####
PUT http://localhost:5000/expenses/2213
Content-Type: application/json

{

  "category": "Jedzenie",
  "date": "2022-09-28",
  "kwota": 66,
  "title": "Sio kwota",
  "opis": "jas opis"
}


####
PATCH http://localhost:5000/expenses/3
Content-Type: application/json

{


  "kwota": 66,

  "opis": "jas opis"
}

####
DELETE http://localhost:5000/expenses/3
####
DELETE http://localhost:5000/expenses/4


